language: python
cache: pip

before_install:
  - travis_retry pip install -U pip
  - pip --version
install:
  - travis_retry pip install tox
  - tox --version
script:
  - travis_retry tox -v

matrix:
  include:
    - python: 3.3
      env: TOXENV=py33
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36

    - python: 3.6
      env: TOXENV=lint

deploy:
- provider: pypi
  repo: greg-hellings/cloud-cleaner
  user: "${PYPI_USER}"
  password: "${PYPI_PASSWORD}"
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    condition: $TOXENV=py36